version: '1'

services:
  database:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: AUTH_SERVICE

  auth_service:
    build: .
    ports:
      - 5050:5050
    restart: unless-stopped
    environment:
      PORT: 5050
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: AUTH_SERVICE
      MYSQL_URL: database:3306
      SECRET_KEY: abcd123!
      ADMIN_USERNAME: ltp
      ADMIN_PASSWORD: 2204
      GIN_MODE: release
    depends_on:
      - database